
; PIC16F887 Configuration Bit Settings

; Assembly source line config statements

#include "p16f887.inc"

; CONFIG1
; __config 0x3FFF
 __CONFIG _CONFIG1, _FOSC_EXTRC_CLKOUT & _WDTE_ON & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
; CONFIG2
; __config 0x3FFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
 CONTADOR EQU 0x20
 CAMBIO EQU 0x21
 MITAD EQU 0x22
 INTERCALADO EQU 0x23
 BARRIDO EQU 0x24
 DELAY_A	EQU 0x25
 DELAY_B	EQU 0x26
 DELAY_C	EQU 0x27

 ORG 0x00 
 GOTO INICIO
 
 
 ORG 0x04
INICIO
    CALL CLEAR_VAR;
    CALL SET_VAR;
    GOTO DELAY_500MS;
    
    
    
CLEAR_VAR
    BCF STATUS,6
    BCF STATUS,5
    CLRW
    CLRF PORTD
    CLRF PORTC
    CLRF INTERCALADO
    CLRF MITAD
    CLRF BARRIDO
    RETURN

SET_VAR
    MOVLW 0xF0
    MOVWF MITAD
    MOVLW 0x55
    MOVWF INTERCALADO
    MOVLW 0x01
    MOVWF BARRIDO
    BSF STATUS,5
    CLRF TRISD
    BSF TRISC, 0
    BCF STATUS,5
    RETURN
    
    
;    CALL COMPROBAR_ENTRADAS
DELAY_500MS
    MOVLW D'4'
    MOVWF DELAY_A
LOOP_A
    MOVLW D'250'
    MOVWF DELAY_B
LOOP_B
    MOVLW D'166'
    MOVWF DELAY_C
LOOP_C
    DECFSZ DELAY_C,1
    GOTO LOOP_C
    DECFSZ DELAY_B,1
    GOTO LOOP_B
    DECFSZ DELAY_A,1
    GOTO LOOP_A
    GOTO PORT_REFRESH
    
    
PORT_REFRESH   
    CALL MODOS
    MOVWF PORTD
    GOTO DELAY_500MS
    
MODOS
    BTFSS PORTC,0
    GOTO CONTAR
    GOTO LUCES_2
    
    
CONTAR
    INCFSZ CONTADOR,F
    MOVLW CONTADOR
    RETURN
;BLINK
;    MOVLW 0x03
;    SUBWF TIPE_MODE
;    BTFSC STATUS, Z
;    GOTO LUCES_1
;    GOTO LUCES_2
    
    
;LUCES_1
;    COMF MITAD
;    MOVLW MITAD
;    RETURN
LUCES_2
    COMF INTERCALADO
    MOVLW INTERCALADO
    RETURN
   
;COMPROBAR_ENTRADAS
;    BCF STATUS, 5
;    BCF STATUS, 6
;    MOVF PORTE, W
;    XORWF ESTADO_ANTERIOR, W
;    ANDLW b'00000001' 
;    BTFSC STATUS, Z
;    RETURN
;    INCF TIPE_MODE
;    RETURN
    
    END





