
; PIC16F887 Configuration Bit Settings

; Assembly source line config statements

#include "p16f887.inc"

; CONFIG1
; __config 0x3FFF
 __CONFIG _CONFIG1, _FOSC_EXTRC_CLKOUT & _WDTE_ON & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
; CONFIG2
; __config 0x3FFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
 CONTADOR EQU 0x20
 CAMBIO EQU 0x21
 MITAD EQU 0x22
 INTERCALADO EQU 0x23
 TIPE_MODE EQU 0x24
 ESTADO_ANTERIOR EQU 0x25

 ORG 0x00 
 GOTO INICIO
 
 
 ORG 0x04
INICIO
    CALL CLEAR_VAR;
    CALL SET_VAR;
    GOTO TIMER;
    
    
    
CLEAR_VAR
    BCF STATUS,6
    BCF STATUS,5
    CLRW
    CLRF PORTD
    CLRF PORTC
    CLRF INTERCALADO
    CLRF MITAD
    CLRF TIPE_MODE
    RETURN

SET_VAR
    MOVLW 0xF0
    MOVWF MITAD
    MOVLW 0x55
    MOVWF INTERCALADO
    BSF STATUS,5
    CLRF TRISD
    BSF TRISC, 0
    BCF STATUS,5
    MOVLW PORTC
    RETURN
    
    
TIMER
    
;    CALL COMPROBAR_ENTRADAS
    GOTO PORT_REFRESH
    
    
PORT_REFRESH   
    CALL MODOS
    MOVWF PORTD
    GOTO TIMER
    
MODOS
    BTFSS PORTC,0
    GOTO CONTAR
    GOTO LUCES_2
    
    
CONTAR
    INCFSZ CONTADOR,W
    RETURN
;BLINK
;    MOVLW 0x03
;    SUBWF TIPE_MODE
;    BTFSC STATUS, Z
;    GOTO LUCES_1
;    GOTO LUCES_2
    
    
;LUCES_1
;    COMF MITAD
;    MOVLW MITAD
;    RETURN
LUCES_2
    COMF INTERCALADO
    MOVLW INTERCALADO
    RETURN
   
;COMPROBAR_ENTRADAS
;    BCF STATUS, 5
;    BCF STATUS, 6
;    MOVF PORTE, W
;    XORWF ESTADO_ANTERIOR, W
;    ANDLW b'00000001' 
;    BTFSC STATUS, Z
;    RETURN
;    INCF TIPE_MODE
;    RETURN
    
    END





